-- Create audit_logs table
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  track_id integer null,
  object_class text null,
  confidence double precision null,
  bbox_x1 integer null,
  bbox_y1 integer null,
  bbox_x2 integer null,
  bbox_y2 integer null,
  frame_number integer null,
  camera_id text null references public.camera_sources(camera_id) on delete cascade,
  direction text null check (direction in ('IN', 'OUT')),
  session_id text null,
  timestamp timestamp with time zone null default now(),
  created_at timestamp with time zone default now()
);

-- Create live_logs table
create table if not exists public.live_logs (
  id bigint generated by default as identity primary key,
  track_id integer null,
  object_class character varying(50) null,
  confidence double precision null,
  bbox_x1 integer null,
  bbox_y1 integer null,
  bbox_x2 integer null,
  bbox_y2 integer null,
  frame_number integer null,
  timestamp timestamp with time zone null default now(),
  camera_id character varying(50) null references public.camera_sources(camera_id) on delete cascade,
  direction character varying(10) null check (direction in ('IN', 'OUT')),
  session_id character varying(100) null,
  created_at timestamp with time zone default now()
);

-- Create simulated_logs table
create table if not exists public.simulated_logs (
  id bigint generated by default as identity primary key,
  track_id integer null,
  object_class character varying(50) null,
  confidence double precision null,
  bbox_x1 integer null,
  bbox_y1 integer null,
  bbox_x2 integer null,
  bbox_y2 integer null,
  frame_number integer null,
  timestamp timestamp with time zone null default now(),
  camera_id character varying(50) null references public.camera_sources(camera_id) on delete cascade,
  direction character varying(10) null check (direction in ('IN', 'OUT')),
  session_id character varying(100) null,
  created_at timestamp with time zone default now()
);

-- Create indexes for efficient querying
create index if not exists audit_logs_camera_id_timestamp_idx on public.audit_logs(camera_id, timestamp);
create index if not exists audit_logs_direction_idx on public.audit_logs(direction);
create index if not exists audit_logs_session_id_idx on public.audit_logs(session_id);

create index if not exists live_logs_camera_id_timestamp_idx on public.live_logs(camera_id, timestamp);
create index if not exists live_logs_direction_idx on public.live_logs(direction);
create index if not exists live_logs_session_id_idx on public.live_logs(session_id);

create index if not exists simulated_logs_camera_id_timestamp_idx on public.simulated_logs(camera_id, timestamp);
create index if not exists simulated_logs_direction_idx on public.simulated_logs(direction);
create index if not exists simulated_logs_session_id_idx on public.simulated_logs(session_id);

-- Enable RLS on all log tables
alter table public.audit_logs enable row level security;
alter table public.live_logs enable row level security;
alter table public.simulated_logs enable row level security;

-- RLS policies for reads (allow all to read)
create policy "Allow audit_logs reads" on public.audit_logs for select using (true);
create policy "Allow live_logs reads" on public.live_logs for select using (true);
create policy "Allow simulated_logs reads" on public.simulated_logs for select using (true);

-- RLS policies for inserts (allow all to insert)
create policy "Allow audit_logs inserts" on public.audit_logs for insert with check (true);
create policy "Allow live_logs inserts" on public.live_logs for insert with check (true);
create policy "Allow simulated_logs inserts" on public.simulated_logs for insert with check (true);
